### ISSUE TITLE
All devices report as not_home.

### ISSUE THREAD

**Issue by SgtBatten** [shaiu/technicolor#1]
Hello,

I have configured the integration successfully. I was hoping to add another method of detecting if my phone was home or not however my phone, and in fact every device, is listed as not_home.

**Comment by AUSF** [comment]
Same for me. Apparently all the connected devices (MAC addresses) are listed in the log, but they are labelled as "not_home".

BTW in the logfile I see messages like this:

_2021-06-28 09:24:44 INFO (MainThread) [custom_components.technicolor.device_tracker] updating state for $f0:51:ea:ca:1d:c5 with ip $None_

where the the $None looks suspicious...

**Comment by shaiu** [comment]
Thank you for your feedback. I'll have a look and get back to you.

**Comment by shaiu** [comment]
@AUSF @SgtBatten I need your help.
I need the html page of your device-modal from your router.
You can find it at: http://192.168.1.1/modals/device-modal.lp (could be that your router has a different ip address)
Please note that this holds all your ip/mac addresses of your router. This is sensitive data. I understand if you don't want to share it so you can just change the numbers to what ever you want. Because all I need is the structure of the page (could be that it's different than mine)
Also what is your router model? You can find that information at: http://192.168.1.1/modals/gateway-modal.lp

Thanks

**Comment by AUSF** [comment]
Hello shaiu and thank you for your work!

My modem is a Technicolor AGHP (sw version AGTHP_2.2.1). It's a device provided by Telecom Italia, commercially labelled TIM HUB.
Attached the device-modal HTML file. I have altered the data without changing the format (anyway It only contains data internal to my network). I have a suspect: my modem interface is in Italian: could it be this the reason why the data parsing is failing?
[device-modal.lp.html.zip](https://github.com/shaiu/technicolor/files/6724583/device-modal.lp.html.zip)

**Comment by shaiu** [comment]
@AUSF I added fix.
Please update the integration through HACS in your HA.
Let me know if it got fixed.

**Comment by AUSF** [comment]
Thank you very much shaiu! It works now! May I ask if it was a problem related to the language used in the modem web interface?
Anyway I appreciate a lot the super quick fix!
All the best!

**Comment by shaiu** [comment]
Hi @AUSF 
It was partly because of the language.
You are using a different model of router so the html is different than mine.
I added a more generic way to scrape the name/ip/mac from the html page.

Thanks

**Comment by SgtBatten** [comment]
@shaiu Thanks Mine is working also now with the update. Awesome.

FYI my model is a Technicolor DJA0230TLS with the following format:

![image](https://user-images.githubusercontent.com/24822223/123708404-b1925b00-d8ae-11eb-9f18-8c50f18e3a1b.png)

**Comment by AUSF** [comment]
Uhm... I was happy to see the status of the devices set to "home" when they are connected, but now I have discovered that the status stay "home" even if they are disconnected...
This is an example of the status of a device after I disconnected it from the wifi:
![image](https://user-images.githubusercontent.com/5352126/123756718-7f3c2a00-d8bd-11eb-836e-d8fb7067fe53.png)

shaiu: could you still have a look to the code of the integration? THANK YOU!

**Comment by shaiu** [comment]
Hi @AUSF , I just fixed this issue this morning (someone else found it as well)
Please update the integration and let me know if it got fixed. 
Thanks

**Comment by AUSF** [comment]
Hi shaiu! I confirm that it seems to be OK now,
Thank you again for your work!
