### ISSUE TITLE
Trigger event

### ISSUE THREAD

**Issue by fatuuse** [shaiu/technicolor#10]
It would be greater if there where and event i HASS on new devices.

When new devices is found on the router, trigger Home Assistant device_tracker_new_device event with data about the device, eg.
trigger.event.data.host_name
trigger.event.data.source_type
trigger.event.data.mac

**Comment by shaiu** [comment]
@fatuuse

I found this:
[https://community.home-assistant.io/t/new-device-tracker-events/287746/2](https://community.home-assistant.io/t/new-device-tracker-events/287746/2)
I didn't try it yet but I think it can solve the issue.

**Comment by shaiu** [comment]
@fatuuse did it work?

**Comment by fatuuse** [comment]
👍
