### ISSUE TITLE
Integration not working anymore with TIM HUB (AGHP = Technicolor DGA4132) sw version AGTHP_2.3.1

### ISSUE THREAD

**Issue by AUSF** [shaiu/technicolor#8]
Hello,

unfortunately my operator has updated the fw on the device from 2.2.1 to 2.3.1 and the device-modal.lp is now completely different! Looking to the html source I think that the needed data is still there, but not visualized in the browser:
![image](https://user-images.githubusercontent.com/5352126/128326108-d50794a1-a8b6-4f11-9bc7-b7c02670fea2.png)

Do we have a chance to see this nice integration working again? :-)

Thanks!

**Comment by shaiu** [comment]
@AUSF Can you provide me with the html itself?

**Comment by AUSF** [comment]
@shaiu I sent you the file with a direct email.

Thank you!

**Comment by AUSF** [comment]
Thank you Shaiu: your fix is working for me!
